name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [mainline, stable]

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file ${{ matrix.version }}/Dockerfile --tag my-image-name:$(date +%s)
